
spring:
  application:
    name: IRCTC-Rest-Api
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true